### ISSUE TITLE
Questions to the client

### ISSUE THREAD

**Issue by dawidgrobert** [Glitched-Bacons/Nizer#1]
Questions that should be asked of the client related to project implementation.

**Comment by Notiooo** [comment]
We would like to give the user the opportunity to choose from the following techniques of evaluating metric to calculate the similarity between images:
- Root mean square error
- Peak signal-to-noise ratio
- Structural Similarity Index
- Feature-based similarity index
- Information theoretic-based Statistic Similarity Measure
- Signal to reconstruction error ratio
- Spectral angle mapper
- Universal image quality index
