### ISSUE TITLE
Home page design

### ISSUE THREAD

**Issue by Notiooo** [Glitched-Bacons/Nizer#4]
What users see when user open users files in the Nizer app.

**Comment by JuliaBoczkowska** [comment]
![homepage_design](https://user-images.githubusercontent.com/56159677/137647130-6fa4bd58-75a6-4f58-bc9e-e4d657f4fce1.png)

**Comment by JuliaBoczkowska** [comment]
![homepage](https://user-images.githubusercontent.com/56159677/142087155-b5179b38-78a3-4070-91fc-3bb2b11c373c.gif)

New homepage design according to the current use case diagram.
